Repository WildCodeSchool-2024-09/toulouse-p2-weatherly, pull requests merged in 2024-11, with the labels that each got.

#3 Title for US of sprint S
  client/src/App.tsx
Labels: CORRECTIONS_DONE, REVIEWED

#4 S0 us00/my feature
  client/src/App.tsx
Labels: CORRECTIONS_DONE, REVIEWED

#5 S0 us01/my feature
  client/src/App.tsx
Labels: CORRECTIONS_DONE, REVIEWED

#7 feat: put the router on motion
  client/package.json
  client/src/App.css
  client/src/App.tsx
  client/src/components/Favorites.tsx
  client/src/components/FiveDays.tsx
  client/src/components/WelcomePage.tsx
  client/src/main.tsx
  package-lock.json
Labels: CONFLICTS_RESOLVED

#6 feat(api-weather): implement functions on city search by name or position
  client/src/library/api-weather.ts
Labels: REVIEWED

#8 chore: add images in src/assets/images
  client/src/assets/images/1.png
  client/src/assets/images/11.png
  client/src/assets/images/12.png
  client/src/assets/images/13.png
  client/src/assets/images/14.png
  client/src/assets/images/15.png
  client/src/assets/images/16.png
  client/src/assets/images/17.png
  client/src/assets/images/18.png
  client/src/assets/images/19.png
  client/src/assets/images/2.png
  client/src/assets/images/20.png
  client/src/assets/images/21.png
  client/src/assets/images/22.png
  client/src/assets/images/23.png
  client/src/assets/images/24.png
  client/src/assets/images/25.png
  client/src/assets/images/26.png
  client/src/assets/images/29.png
  client/src/assets/images/3.png
  client/src/assets/images/30.png
  client/src/assets/images/31.png
  client/src/assets/images/32.png
  client/src/assets/images/33.png
  client/src/assets/images/34.png
  client/src/assets/images/35.png
  client/src/assets/images/36.png
  client/src/assets/images/37.png
  client/src/assets/images/38.png
  client/src/assets/images/39.png
  client/src/assets/images/4.png
  client/src/assets/images/40.png
  client/src/assets/images/41.png
  client/src/assets/images/42.png
  client/src/assets/images/43.png
  client/src/assets/images/44.png
  client/src/assets/images/5.png
  client/src/assets/images/6.png
  client/src/assets/images/7.png
  client/src/assets/images/8.png
  client/src/assets/images/map.png
  client/src/assets/images/sun-rise-set.png
  client/src/assets/images/sunrise.png
  client/src/assets/images/sunset.png
Labels: REVIEWED

#9 S2 us02/component summary today weather
  client/.env.sample
  client/.gitignore
  client/src/App.tsx
  client/src/components/CityLocation.tsx
  client/src/components/Footer.tsx
  client/src/components/Header.tsx
  client/src/components/Summary.tsx
  client/src/components/SunRise.tsx
  client/src/components/SunSet.tsx
  client/src/components/SunTime.tsx
  client/src/components/TodayWeather.tsx
  client/src/components/WeatherParameter.tsx
  client/src/components/WelcomePage.tsx
  client/src/contexts/CityContext.ts
  client/src/contexts/WeatherContext.ts
  client/src/library/api-weather.ts
Labels: CORRECTIONS_DONE, REVIEWED

#11 fix: add icons for pages and logo
  client/src/assets/images/Favoris.png
  client/src/assets/images/five-days.png
  client/src/assets/images/logo.png
  client/src/assets/images/today.png
  client/src/components/Header.tsx
Labels: REVIEWED

#12 favorite city from search bar
  client/src/components/SearchBar.tsx
  client/src/library/api-weather.ts
Labels: REVIEWED

#13 feat: implement five days component
  client/src/components/FiveDays.tsx
Labels: REVIEWED

#15 S2 us01/component today weather
  client/src/App.css
  client/src/App.tsx
  client/src/components/CityLocation.tsx
  client/src/components/Footer.tsx
  client/src/components/Header.tsx
  client/src/components/Summary.tsx
  client/src/components/SunRise.tsx
  client/src/components/SunSet.tsx
  client/src/components/SunTime.tsx
  client/src/components/TodayWeather.tsx
  client/src/components/WeatherParameter.tsx
  client/src/components/WelcomePage.tsx
  client/src/style-css/CityLocation.css
  client/src/style-css/Footer.css
  client/src/style-css/Header.css
  client/src/style-css/ResponsiveBox.css
  client/src/style-css/Summary.css
  client/src/style-css/SunTime.css
  client/src/style-css/Sunrise.css
  client/src/style-css/Sunset.css
  client/src/style-css/TodayWeather.css
  client/src/style-css/WeatherParameter.css
  client/src/style-css/WelcomePage.css
Labels: CONFLICTS_RESOLVED, REVIEWED

#14 S3 us12/header css
  client/src/components/Header.css
  client/src/components/Header.tsx
  client/src/components/WelcomePage.tsx
Labels: REVIEWED

#16 S1 us01/use city context refactor
  client/src/App.tsx
  client/src/components/CityFavorite.tsx
  client/src/components/CityFavorites.tsx
  client/src/components/CityLocation.tsx
  client/src/components/Favorites.tsx
  client/src/components/SearchBar.tsx
  client/src/contexts/CityContext.ts
  client/src/contexts/CityContextProvider.tsx
  client/src/library/api-weather.ts
  client/src/main.tsx
Labels: REVIEWED

#17 style: make favorites page responsive and respect the sketch
  client/src/assets/images/map.svg
  client/src/components/Favorites.tsx
  client/src/components/SearchBar.tsx
  client/src/style-css/Favorites.css
Labels: REVIEWED

#18 style: add five days style and media queries
  client/src/components/FiveDays.tsx
  client/src/style-css/FiveDaysStyle.css
  package-lock.json
Labels: REVIEWED

#19 fix: put context of weather end propagate the choice of city and its weather forecast to other pages
  client/src/App.tsx
  client/src/components/CityFavorite.tsx
  client/src/components/Summary.tsx
  client/src/components/SunRise.tsx
  client/src/components/SunSet.tsx
  client/src/components/TodayWeather.tsx
  client/src/components/WeatherParameter.tsx
  client/src/contexts/WeatherContext.ts
  client/src/contexts/WeatherContextProvider.tsx
  client/src/style-css/Favorites.css
Labels: REVIEWED

#20 fix: modify css header & footer
  client/src/assets/images/logo.png
  client/src/components/Header.css
  client/src/style-css/CityLocation.css
  client/src/style-css/FiveDaysStyle.css
  client/src/style-css/Footer.css
Labels: REVIEWED

#21 S3 us06/five days style
  client/index.html
  client/src/assets/images/logo-flaticon.png
Labels: REVIEWED

#22 fix: call asynchronous function getCurrentPosition in useEffect
  client/src/contexts/CityContextProvider.tsx
  client/src/contexts/WeatherContextProvider.tsx
  client/src/library/api-weather.ts
Labels: REVIEWED

#23 feat: use data returned by API in five days page
  client/src/components/Favorites.tsx
  client/src/components/FiveDays.tsx
Labels: REVIEWED

#24 feat: add map for favorite cities
  client/package.json
  client/src/components/Favorites.tsx
  client/src/style-css/Favorites.css
Labels: REVIEWED

#25 feat: update map when city was selected
  client/src/components/CityFavorite.tsx
  client/src/components/Favorites.tsx
  client/src/components/MapLeaflet.tsx
  client/src/contexts/CityContextProvider.tsx
  client/src/contexts/WeatherContextProvider.tsx
  client/src/library/api-weather.ts
Labels: REVIEWED

#26 fix: design of the whole websign for consistancy
  client/src/style-css/CityLocation.css
  client/src/style-css/FiveDaysStyle.css
  client/src/style-css/Summary.css
  client/src/style-css/TodayWeather.css
  client/src/style-css/WelcomePage.css
Labels: REVIEWED

#27 feat: add feature favorite selected
  client/src/components/CityFavorite.tsx
  client/src/components/CityFavorites.tsx
  client/src/style-css/Favorites.css
Labels: REVIEWED

#28 feat: add city from map to favorites
  client/src/components/CityFavorite.tsx
  client/src/components/CityFavorites.tsx
  client/src/components/Favorites.tsx
  client/src/components/MapLeaflet.tsx
  client/src/style-css/Favorites.css
Labels: REVIEWED

#29 feat: add a map with animation of rain to Welcome page
  client/src/components/MapLeaflet.tsx
  client/src/components/MapRainViewer.tsx
  client/src/components/WelcomePage.tsx
  client/src/library/api-weather.ts
  client/src/services/RainTyleLayerApi.ts
  client/src/style-css/Favorites.css
  client/src/style-css/WelcomePage.css
Labels: REVIEWED

#30 fix: final design for the new map added and favorites components
  client/src/style-css/Favorites.css
  client/src/style-css/TodayWeather.css
  client/src/style-css/WeatherParameter.css
  client/src/style-css/WelcomePage.css
Labels: REVIEWED
